# Generated by Django 3.0.3 on 2020-08-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200324_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Hu Bo', max_length=100, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
