# Generated by Django 3.0.3 on 2020-08-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200810_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
