# Generated by Django 3.0.3 on 2020-08-10 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0003_affiliation_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='affiliation_logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='affiliation name'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Affiliation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
