# Generated by Django 3.0.3 on 2020-09-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Team Member', max_length=100, verbose_name='full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='publications/', verbose_name='PDF file'),
        ),
    ]
